services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: GSPREAD_JSON
        value: ${GSPREAD_JSON}
